apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      #allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5zyboqbxZ+XZ6b/OSIynbQk+0ftoC7F0i3zOIRJIky9c7hoVWFSpJmjYNj5WdmoneyaZe4/qnau0/tn/SdkC64cSx7osJkPsBYzgTb689gQpaeFFdmLlhEorQC2Zuh5CEtAIgwz0tEO1YhmYKevCUp/
bvO5L4ru8tDnBtuK8CE4xLJpqiGF7QAu9U6JBP8iGHETxlFz0dcgiXQ9AVVbkO5Xu1cNYd4czf4XYNGLGtfdkViq67lQzcjQVYtpQi5GykCGCzyi7wHYMbVd/o2akrG20XWKuAAZqIsISYb6bvjw8Gj4CScQchvC5IloYO3WvBBxpwRrllJVtFkFuQHem7
PTIhF81M7F93Pcq5tMZsahuQNw0oalG2rMh0hsZmJIwxDWNeSLgVPX7L2FZuMHZDkSAoIhFhbzSXkpLki63CtnGQn9l32gNMjgwLtD1Bg73QDqnoHqP9oxL79mfQIMMa8NWiuD3652pfNPce0OBbz5yAgqe73W/ABrs7FAIwuak= garipe@garipe-MS-
7680"
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 50
    ssh:
      #allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5zyboqbxZ+XZ6b/OSIynbQk+0ftoC7F0i3zOIRJIky9c7hoVWFSpJmjYNj5WdmoneyaZe4/qnau0/tn/SdkC64cSx7osJkPsBYzgTb689gQpaeFFdmLlhEorQC2Zuh5CEtAIgwz0tEO1YhmYKevCUp/
bvO5L4ru8tDnBtuK8CE4xLJpqiGF7QAu9U6JBP8iGHETxlFz0dcgiXQ9AVVbkO5Xu1cNYd4czf4XYNGLGtfdkViq67lQzcjQVYtpQi5GykCGCzyi7wHYMbVd/o2akrG20XWKuAAZqIsISYb6bvjw8Gj4CScQchvC5IloYO3WvBBxpwRrllJVtFkFuQHem7
PTIhF81M7F93Pcq5tMZsahuQNw0oalG2rMh0hsZmJIwxDWNeSLgVPX7L2FZuMHZDkSAoIhFhbzSXkpLki63CtnGQn9l32gNMjgwLtD1Bg73QDqnoHqP9oxL79mfQIMMa8NWiuD3652pfNPce0OBbz5yAgqe73W/ABrs7FAIwuak= garipe@garipe-MS-
7680"
