#-------------------------------------------------------------
# Manifest File to create Simple Deployment with Labels
#
# Copyleft (c) by Denis Astahov 2020
#-------------------------------------------------------------
apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment # Название Deployment
  labels:
    app : my-k8s-application # Теги, необязательно.

spec:
  selector: # Какими Pods будет работать.
    matchLabels:
      project: kgb # Название проекта (пофиг что там)
  
  template: # Какими Pods будет работь
    metadata:
      labels:
        project: kgb # Должен совпасть то что выше.
    
    spec:   # Собственно сам контейнер  
      containers:
        - name : kgb-web
          image: adv4000/k8sphp:latest # Указываем контейнер
          ports:
            - containerPort: 80
