apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-gpu
  labels:
     app: http-server1
spec:
  nodeSelector: # Это необходимо для определения на какой нод будем ставить, т.е. те селекторы должны пристуствовать в лейболах нода.
    gpu: "true"
  containers:
  - name: app-kuber-container
    image: bokovets/kuber:0.1
    ports:
    - containerPort: 8000
