apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc1
spec:
  replicas: 2
  selector:
    app: http-server1
  template:
    metadata:
      name: kuber-app
      labels:
        app: http-server1
    spec:
      containers:
      - name: http-server-image
        image: bokovets/kuber
        ports:
        - containerPort: 8000
